### ISSUE TITLE
Add Gapher (OpenSource UML, SysML, RAAML, and C4 modeler)

### ISSUE THREAD

**Issue by sboisson** [shubhamgrg04/awesome-diagramming#25]
Gaphor is a UML, SysML, RAAML, and C4 modeling application. It is designed to be easy to use, while still being powerful. Gaphor implements a fully-compliant UML 2 data model, so it is much more than a picture drawing tool. You can use Gaphor to quickly visualize different aspects of a system as well as create complete, highly complex models.

https://gaphor.org
https://github.com/gaphor/gaphor

**Comment by shubhamgrg04** [comment]
Adding Gaphor to others section, as needs to be evaluated in future. Ther are couple of issues currently which makes it less easy to use:
- it doesn't have a web version, which becomes really handy
- the website is showing chinese text, although language selected is english
